A program that reads and processes images for a Gradient Boosting Classifier to classify as images as good, blacked-out, saturated, or blurry.

In [1]:
import numpy as np
import pandas as pd
import os
from glob import glob
import matplotlib.pyplot as plt
%matplotlib inline
import cv2

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn import linear_model
from sklearn import svm
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

import sys
sys.path.insert(0, 'C:/Users/micha/github/uav-image-analysis/scripts/')
import fit_models

C:\Users\micha\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [2]:
df_train = pd.read_csv('/Users/micha/ea-applications/data/test-images.csv')

paths = '/Users/micha/ea-applications/data/training-test-images/Thermal/mytest/*MEDIA/'

train_images = fit_models.read_images(paths)

y = np.array(df_train['Label'])

y = df_train['Label'].values

X_train, X_test, y_train, y_test = train_test_split(train_images, y, random_state=42, test_size=0.4)

print(df_train.head())
print(X_train.shape)
print(y_train)

(431, 327680)
  Image Date     MEDIA Image_Name  Label Unnamed: 4
0  2/16/2019  100MEDIA   DJI_0001      2        NaN
1  2/16/2019  100MEDIA   DJI_0002      2        NaN
2  2/16/2019  100MEDIA   DJI_0003      2        NaN
3  2/16/2019  100MEDIA   DJI_0004      2        NaN
4  2/16/2019  100MEDIA   DJI_0005      2        NaN
(258, 327680)
[0 0 0 0 0 0 0 0 0 2 0 0 3 0 0 0 3 0 0 0 0 0 2 0 0 2 0 0 0 0 0 0 3 2 0 0 0
 0 2 3 0 2 0 3 0 0 2 0 0 0 0 2 0 0 3 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 3 0
 0 0 0 1 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 2 1 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0
 3 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 2 0 3 0 0 0 0 0
 3 0 0 0 0 0 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 2 3 0 2 0 0 0 0
 1 0 0 0 3 3 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 2 0 0 0 0 0 0 1 2 0 0 0 0 0 0]


In [3]:
# Run gradient boosting classifier
model = GradientBoostingClassifier()
model_boosting, probabilities, y_pred = fit_models.supervised_models(model, X_train, y_train, X_test, y_test)
print(probabilities)

             precision    recall  f1-score   support

          0       0.84      0.94      0.89       133
          1       0.86      0.75      0.80         8
          2       0.47      0.50      0.48        14
          3       0.00      0.00      0.00        18

avg / total       0.72      0.80      0.76       173

[4.69650870e-06 1.69103156e-05 2.98603941e-05 1.96985719e-05
 5.48940288e-05 1.69103156e-05 1.69103156e-05 2.45760717e-03
 6.86493277e-05 1.69103156e-05 2.29877014e-05 1.69099461e-05
 2.05051215e-04 1.95920443e-05 1.69096493e-05 1.69103156e-05
 1.66894741e-05 6.34354430e-05 1.68718917e-05 1.69103156e-05
 5.59599563e-05 1.69103156e-05 1.69103156e-05 1.69103156e-05
 1.69103156e-05 1.00908212e-04 3.84035973e-05 1.69102390e-05
 1.69103156e-05 1.69103156e-05 1.69103156e-05 1.69103156e-05
 3.95174741e-05 1.86390126e-05 9.98965565e-01 1.69103156e-05
 2.94413572e-04 2.34888559e-04 1.69103156e-05 9.77498163e-01
 1.69103156e-05 1.69098007e-05 1.69103156e-05 1.69103156e-05
 1.69103

In [4]:
print(confusion_matrix(y_test, y_pred))

[[125   0   6   2]
 [  2   6   0   0]
 [  7   0   7   0]
 [ 15   1   2   0]]


In [5]:
np.set_printoptions(precision=2)

# Plot non-normalized confusion matrix
fit_models.plot_confusion_matrix(y_test, y_pred, classes=class_labels,
                      title='Confusion matrix, without normalization')

# Plot normalized confusion matrix
fit_models.plot_confusion_matrix(y_test, y_pred, classes=class_labels, normalize=True,
                      title='Normalized confusion matrix')

plt.show()

NameError: name 'class_labels' is not defined

In [ ]:
# save the model to disk
filename = 'finalized_model.sav'
pickle.dump(model_boosting, open(filename, 'wb'))